In [9]:
import torch
import numpy as np

In [6]:
#Challenge 1
scalar_t = torch.tensor(1)
vector_t = torch.tensor([2,3,5,7])
matrix_t = torch.tensor([[1,2],[3,4],[5,6]])
print(scalar_t)
print(vector_t)
print(matrix_t)

'''
Shape Describes the size of each dimension and dimensionality represents the number 
of dimensions on the whole'''

tensor(1)
tensor([2, 3, 5, 7])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


'\nShape Describes the size of each dimension and dimensionality represents the number \nof dimensions on the whole'

In [7]:
#Challenge 2
zeros = torch.zeros(2,3)
ones = torch.ones(2,3)
random = torch.rand(2,3)

print(zeros)
print(ones)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7923, 0.5776, 0.1099],
        [0.7806, 0.1301, 0.8154]])


In [8]:
#Challenge 3
x = torch.tensor([2,3,5,7])
y = torch.tensor([1,3,6,4])

print('Addition:',x+y)
print('Multiplication:',x*y)
print('Scalar Multiplication:',x*2)

Addition: tensor([ 3,  6, 11, 11])
Multiplication: tensor([ 2,  9, 30, 28])
Scalar Multiplication: tensor([ 4,  6, 10, 14])


In [15]:
#Challenge 4
arr = np.array([2,3,5,7])
t = torch.tensor(arr)
print(t, arr)
b=t.numpy()
b

tensor([2, 3, 5, 7]) [2 3 5 7]


array([2, 3, 5, 7])

In [19]:
#Challenge 5
x=torch.tensor(2.0, requires_grad= True)
y = x*(x+3)
y.backward()
x.grad

tensor(7.)