In [ ]:
#Challenge 1
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np
data = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 6],
    [6, 7]
])
std= StandardScaler()
x_scaled= std.fit_transform(data)

pca= PCA(n_components=2)
x_reduced= pca.fit_transform(x_scaled)

print('Original Shape:',data.shape)
print('Reduced Shape:',x_reduced.shape)
print('Explained Varience Ratio:',pca.explained_variance_ratio_)
print('Components:\n',pca.components_)

'''No Columns change because the initial is also 2 and the final is set to be 2'''


Original Shape: (6, 2)
Reduced Shape: (6, 2)
Explained Varience Ratio: [1.00000000e+00 1.62056986e-32]
Components:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [ ]:
#Challenge 2
data = [
    [10, 20, 30, 40],
    [12, 22, 31, 42],
    [15, 25, 35, 45],
    [20, 30, 40, 50],
    [25, 35, 45, 55],
    [30, 40, 50, 60],
    [35, 45, 55, 65],
    [40, 50, 60, 70]
]
std= StandardScaler()
x_scaled= std.fit_transform(data)

pca= PCA(n_components=2)
x_reduced= pca.fit_transform(x_scaled)

print(pca.explained_variance_ratio_)
print(pca.explained_variance_ratio_.sum())
''' it retains 100 percent of the information with just 2 components'''

[9.99844555e-01 1.55444606e-04]
1.0


In [ ]:
#Challenge 3
compo=[1,2,3,4]
for n in compo:
    pca=PCA(n_components=n)
    pca.fit_transform(x_scaled)
    print(f'components:{n}  => Ratio of information Retained:{pca.explained_variance_ratio_.sum()}')
'''one component is enough to give 99 percent information, 2 component is enough to get 100 percent of the info'''

components:1  => Ratio of information Retained:0.999844555393591
components:2  => Ratio of information Retained:1.0
components:3  => Ratio of information Retained:1.0
components:4  => Ratio of information Retained:1.0


In [ ]:
#Challenge 4
data = [
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12],
    [5, 10, 15],
    [6, 12, 18]
]

x_scaled= std.fit_transform(data)
pca=PCA(n_components=2)
x_reduced= pca.fit_transform(x_scaled)

print(pca.components_)
''' the Components actually represent the weight co efficient each of the 
feature have for a pca component row, the feature are the coluumns,
ex the values are around -1 to 1, when the value is greater than 0 that means when
that feature increases the pca value calculated , vice versa'''

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.81649658 -0.40824829 -0.40824829]]


In [ ]:
#Challenge 5
from sklearn.pipeline import make_pipeline
from sklearn.cluster import KMeans

from sklearn.datasets import make_blobs

X, y = make_blobs(
    n_samples=300,
    n_features=5,
    centers=3,
    cluster_std=2.0,
    random_state=42
)
std=StandardScaler()
pca=PCA(n_components=2)
kmeans= KMeans(n_clusters=3, random_state=5, n_init=10)

pipe=make_pipeline(std,pca,kmeans)
labels= pipe.fit_predict(X)
print('Explained Variance Ratio:',pipe[1].explained_variance_ratio_)
print('Total Explained Variance Ratio:',pipe[1].explained_variance_ratio_.sum())
print(labels)
'''A: Because Reducing the components and features to lesser features
with the same to similar amount of information is easier to visualize
and compute

   B:because pca decomposes the number of features and k means perfectly
   works with the less number of features when compared to more features
   
   
   C:I think Around 20 percent information loss will be present ig'''

Explained Variance Ratio: [0.45207262 0.3431439 ]
Total Explained Variance Ratio: 0.7952165117758538
[2 2 0 1 2 0 0 0 2 2 0 1 1 0 2 1 2 0 2 0 2 2 1 2 0 1 1 2 1 1 2 0 0 1 2 0 1
 0 0 0 1 0 1 0 2 0 1 1 1 0 0 0 2 2 2 1 2 2 1 1 2 1 2 1 0 1 0 0 2 1 1 0 2 1
 1 0 1 0 1 0 0 1 2 0 0 2 2 1 2 2 1 1 1 2 1 2 2 1 2 2 1 0 2 1 1 0 2 2 2 2 1
 2 2 1 2 2 2 0 0 1 2 1 0 2 0 0 2 1 2 0 2 1 0 0 2 0 2 1 1 2 0 1 2 1 2 2 2 2
 0 0 0 1 0 0 2 1 0 2 2 2 0 1 2 0 0 2 0 0 2 2 2 0 1 1 2 2 1 2 1 0 1 1 0 0 1
 2 2 0 0 1 1 2 0 1 1 1 2 0 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 1 2 1 0 0 2 0 1
 2 1 1 0 2 2 2 1 1 1 1 1 1 0 2 1 0 2 1 0 0 0 1 2 1 0 0 1 0 1 2 1 0 2 2 2 0
 0 0 2 0 1 0 1 1 2 1 0 2 2 2 2 1 2 1 2 1 0 0 1 2 0 2 2 0 2 0 2 1 1 2 1 0 1
 0 0 0 1]
